const colors = {
  light: {
    text: "#0F0A1E",
    tint: "#7C3AED",
    background: "#F8F7FF",
    foreground: "#0F0A1E",
    card: "#FFFFFF",
    cardForeground: "#0F0A1E",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#EDE9FE",
    secondaryForeground: "#4C1D95",
    muted: "#F3F4F6",
    mutedForeground: "#6B7280",
    accent: "#3B82F6",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E5E7EB",
    input: "#E5E7EB",
    surface: "#FFFFFF",
    surfaceElevated: "#F9F8FF",

    anonymousBg: "#1A0533",
    anonymousPrimary: "#A855F7",
    anonymousCard: "#2D1047",
    anonymousBorder: "#4C2A7A",
    anonymousText: "#F3E8FF",
    anonymousMuted: "#9CA3AF",

    success: "#10B981",
    warning: "#F59E0B",
    info: "#3B82F6",

    tabBar: "#FFFFFF",
    tabBarBorder: "#E5E7EB",
    headerBg: "#FFFFFF",
  },
  dark: {
    text: "#F3E8FF",
    tint: "#A855F7",
    background: "#0F0A1E",
    foreground: "#F3E8FF",
    card: "#1A0F2E",
    cardForeground: "#F3E8FF",
    primary: "#8B5CF6",
    primaryForeground: "#FFFFFF",
    secondary: "#2D1B69",
    secondaryForeground: "#DDD6FE",
    muted: "#1F1535",
    mutedForeground: "#9CA3AF",
    accent: "#60A5FA",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2D1B69",
    input: "#2D1B69",
    surface: "#1A0F2E",
    surfaceElevated: "#21133A",

    anonymousBg: "#0A0015",
    anonymousPrimary: "#A855F7",
    anonymousCard: "#1A0533",
    anonymousBorder: "#3D1A6E",
    anonymousText: "#F3E8FF",
    anonymousMuted: "#6B7280",

    success: "#10B981",
    warning: "#F59E0B",
    info: "#60A5FA",

    tabBar: "#0F0A1E",
    tabBarBorder: "#2D1B69",
    headerBg: "#0F0A1E",
  },
  radius: 12,
};

export default colors;
